import { IRecipe } from "../pages/Recipes";

export const mockRecipes: IRecipe[] = [
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    },
    {
        name: "Salamipizza testi",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        instructions: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam a iusto mollitia, repudiandae dolore natus!",
        image: "",
        ingredients: [{name: "Test", amount: 5, unit: "kpl"}],
        comments: [],
        author: {name: "Pekka", _id: "adsdasd", favorites: []},
        favoritedBy: [],
        _id: "dsfadasdad"
    }]

